/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    JsonDiffNode: typeof import('./components/json/DiffNode.vue')['default']
    JsonDiffTree: typeof import('./components/json/DiffTree.vue')['default']
    JsonEditor: typeof import('./components/json/Editor.vue')['default']
    JsonOutput: typeof import('./components/json/Output.vue')['default']
    JsonPanel: typeof import('./components/json/Panel.vue')['default']
    JsonStatCard: typeof import('./components/json/StatCard.vue')['default']
    JsonTree: typeof import('./components/json/Tree.vue')['default']
    JsonTreeNode: typeof import('./components/json/TreeNode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiAppBadge: typeof import('./components/ui/AppBadge.vue')['default']
    UiAppButton: typeof import('./components/ui/AppButton.vue')['default']
    UiAppEmptyState: typeof import('./components/ui/AppEmptyState.vue')['default']
    UiAppIcon: typeof import('./components/ui/AppIcon.vue')['default']
    UiAppPageLoader: typeof import('./components/ui/AppPageLoader.vue')['default']
    UiAppSkeleton: typeof import('./components/ui/AppSkeleton.vue')['default']
    UiAppSpinner: typeof import('./components/ui/AppSpinner.vue')['default']
    UiAppText: typeof import('./components/ui/AppText.vue')['default']
    UiAppToast: typeof import('./components/ui/AppToast.vue')['default']
    UiAppTooltip: typeof import('./components/ui/AppTooltip.vue')['default']
    UiThemeToggle: typeof import('./components/ui/ThemeToggle.vue')['default']
  }
}
